"""Alterar campo prazo_entrega da tabela cotacoes de Date para Integer

Revision ID: 1fc90ce64182
Revises: 9842253b671d
Create Date: 2025-08-28 10:24:58.158795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc90ce64182'
down_revision = '9842253b671d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cotacoes', 'prazo_entrega',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cotacoes', 'prazo_entrega',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
