"""Alterar campo prazo_entrega de Date para Integer

Revision ID: 9842253b671d
Revises: db7010d614bb
Create Date: 2025-08-28 10:21:44.515565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9842253b671d'
down_revision = 'db7010d614bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pesquisas_mercado', 'prazo_entrega',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pesquisas_mercado', 'prazo_entrega',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
