"""Adiciona campo data_entrada_status para rastrear tempo em cada status

Revision ID: db7010d614bb
Revises: 
Create Date: 2025-04-29 17:10:07.906011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7010d614bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotacoes', sa.Column('data_entrada_status', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotacoes', 'data_entrada_status')
    # ### end Alembic commands ###
